{{- $apiService := .Values.controller.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-controller-worker" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or $apiService.annotations .Values.commonAnnotations }}
  annotations:
    {{- if $apiService.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" $apiService.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ $apiService.type }}
  {{- if and $apiService.clusterIP (eq $apiService.type "ClusterIP") }}
  clusterIP: {{ $apiService.clusterIP }}
  {{- end }}
  {{- if $apiService.sessionAffinity }}
  sessionAffinity: {{ $apiService.sessionAffinity }}
  {{- end }}
  {{- if $apiService.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" $apiService.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq $apiService.type "LoadBalancer") (eq $apiService.type "NodePort") }}
  externalTrafficPolicy: {{ $apiService.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq $apiService.type "LoadBalancer") (not (empty $apiService.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ $apiService.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq $apiService.type "LoadBalancer") (not (empty $apiService.loadBalancerIP)) }}
  loadBalancerIP: {{ $apiService.loadBalancerIP }}
  {{- end }}
  {{- if $apiService.externalIPs }}
  externalIPs: {{ toYaml $apiService.externalIPs | nindent 4 }}
  {{- end }}
  ports:
    - name: api
      port: {{ $apiService.ports.api }}
      targetPort: api
      protocol: TCP
    {{- if $apiService.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" $apiService.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
