{{- $workerService := .Values.controller.workerService -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-controller-worker" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}d
  {{- if or $workerService.annotations .Values.commonAnnotations }}
  annotations:
    {{- if $workerService.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" $workerService.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ $workerService.type }}
  {{- if and $workerService.clusterIP (eq $workerService.type "ClusterIP") }}
  clusterIP: {{ $workerService.clusterIP }}
  {{- end }}
  {{- if $workerService.sessionAffinity }}
  sessionAffinity: {{ $workerService.sessionAffinity }}
  {{- end }}
  {{- if $workerService.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" $workerService.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq $workerService.type "LoadBalancer") (eq $workerService.type "NodePort") }}
  externalTrafficPolicy: {{ $workerService.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq $workerService.type "LoadBalancer") (not (empty $workerService.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ $workerService.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq $workerService.type "LoadBalancer") (not (empty $workerService.loadBalancerIP)) }}
  loadBalancerIP: {{ $workerService.loadBalancerIP }}
  {{- end }}
  {{- if $workerService.externalIPs }}
  externalIPs: {{ toYaml $workerService.externalIPs | nindent 4 }}
  {{- end }}
  ports:
    - name: worker-api
      port: {{ $workerService.ports.worker }}
      targetPort: worker-api
      protocol: TCP
    {{- if $workerService.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" $workerService.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
