{{- $credentialSecretName := include "distworker.credentials-secret-name" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $credentialSecretName | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-50"
data:
  mongodb-uri: {{ .Values.mongodb.uri | b64enc }}
